import type { PersonalLink } from "@/types";

export const LINK_CATEGORIES = {
    WATCH_LISTEN: "Watch & Listen",
    CONNECT_CHAT: "Connect & Chat",
    READ_WRITE: "Read & Write",
    PROFESSIONAL_CREATIVE: "Professional & Creative",
} as const;

export const DEFAULT_LINKS: PersonalLink[] = [
    {
        id: "1",
        title: "YouTube",
        url: "https://www.youtube.com/@TheRohitDudi",
        icon: "youtube",
        visible: true,
        order: 0,
        category: LINK_CATEGORIES.WATCH_LISTEN,
        description: "Science & philosophy, explained simply",
    },
    {
        id: "2",
        title: "Instagram",
        url: "https://www.instagram.com/TheRohitDudi",
        icon: "instagram",
        visible: true,
        order: 1,
        category: LINK_CATEGORIES.CONNECT_CHAT,
    },
    {
        id: "3",
        title: "X",
        url: "https://x.com/TheRohitDudi",
        icon: "twitter",
        visible: true,
        order: 2,
        category: LINK_CATEGORIES.CONNECT_CHAT,
        description: "Climate Activist · Data Scientist · YouTuber",
    },
    {
        id: "4",
        title: "Telegram",
        url: "https://t.me/TheRohitDudi",
        icon: "telegram",
        visible: true,
        order: 3,
        category: LINK_CATEGORIES.CONNECT_CHAT,
    },
    {
        id: "5",
        title: "Pinterest",
        url: "https://in.pinterest.com/TheRohitDudi/",
        icon: "pinterest",
        visible: true,
        order: 4,
        category: LINK_CATEGORIES.PROFESSIONAL_CREATIVE,
    },
    {
        id: "6",
        title: "Patreon",
        url: "https://www.patreon.com/c/TheRohitDudi",
        icon: "patreon",
        visible: true,
        order: 5,
        category: LINK_CATEGORIES.PROFESSIONAL_CREATIVE,
    },
    {
        id: "7",
        title: "LinkedIn",
        url: "https://www.linkedin.com/in/TheRohitDudi/",
        icon: "linkedin",
        visible: true,
        order: 6,
        category: LINK_CATEGORIES.PROFESSIONAL_CREATIVE,
    },
    {
        id: "8",
        title: "Tumblr",
        url: "https://www.tumblr.com/therohitdudi",
        icon: "tumblr",
        visible: true,
        order: 7,
        category: LINK_CATEGORIES.READ_WRITE,
    },
    {
        id: "9",
        title: "GitHub",
        url: "https://github.com/TheRohitDudi",
        icon: "github",
        visible: true,
        order: 8,
        category: LINK_CATEGORIES.PROFESSIONAL_CREATIVE,
        description: "Data Scientist. Full Stack Engineer.",
    },
    {
        id: "10",
        title: "Discord",
        url: "https://discord.gg/TheRohitDudi",
        icon: "discord",
        visible: true,
        order: 9,
        category: LINK_CATEGORIES.CONNECT_CHAT,
    },
    {
        id: "11",
        title: "Facebook",
        url: "https://www.facebook.com/profile.php?id=61583425590511",
        icon: "facebook",
        visible: true,
        order: 10,
        category: LINK_CATEGORIES.CONNECT_CHAT,
    },
    {
        id: "12",
        title: "Threads",
        url: "https://www.threads.net/@TheRohitDudi",
        icon: "threads",
        visible: true,
        order: 11,
        category: LINK_CATEGORIES.CONNECT_CHAT,
    },
    {
        id: "13",
        title: "Reddit",
        url: "https://www.reddit.com/user/TheRohitDudi/",
        icon: "reddit",
        visible: true,
        order: 12,
        category: LINK_CATEGORIES.CONNECT_CHAT,
    },
    {
        id: "14",
        title: "SoundCloud",
        url: "https://soundcloud.com/TheRohitDudi",
        icon: "soundcloud",
        visible: true,
        order: 13,
        category: LINK_CATEGORIES.WATCH_LISTEN,
    },
    {
        id: "15",
        title: "Spotify Show",
        url: "https://open.spotify.com/show/5dYpLediGaquOoXGxh2Ttj",
        icon: "spotify",
        visible: true,
        order: 14,
        category: LINK_CATEGORIES.WATCH_LISTEN,
        description: "Official Science-Philosophy podcast",
    },
    {
        id: "16",
        title: "WhatsApp Channel",
        url: "https://whatsapp.com/channel/0029VaAFT0cFy727f8XzfR18",
        icon: "whatsapp",
        visible: true,
        order: 15,
        category: LINK_CATEGORIES.CONNECT_CHAT,
    },
    {
        id: "17",
        title: "Steam Community",
        url: "https://steamcommunity.com/id/TheRohitDudi",
        icon: "steam",
        visible: true,
        order: 16,
        category: LINK_CATEGORIES.PROFESSIONAL_CREATIVE,
    },
    {
        id: "18",
        title: "Discord Community",
        url: "https://discord.gg/g47zAAg98",
        icon: "discord",
        visible: true,
        order: 17,
        category: LINK_CATEGORIES.CONNECT_CHAT,
    },
    {
        id: "19",
        title: "Twitch",
        url: "https://www.twitch.tv/therohitdudi",
        icon: "twitch",
        visible: true,
        order: 18,
        category: LINK_CATEGORIES.WATCH_LISTEN,
    },
    {
        id: "20",
        title: "Quora Space",
        url: "https://therohitdudi.quora.com/",
        icon: "quora",
        visible: true,
        order: 19,
        category: LINK_CATEGORIES.CONNECT_CHAT,
    },
    {
        id: "21",
        title: "Bluesky",
        url: "https://bsky.app/profile/rohitdudi.com",
        icon: "bluesky",
        visible: true,
        order: 20,
        category: LINK_CATEGORIES.CONNECT_CHAT,
    },
    {
        id: "22",
        title: "Mastodon",
        url: "https://mastodon.social/@RohitChoudhary",
        icon: "mastodon",
        visible: true,
        order: 21,
        category: LINK_CATEGORIES.CONNECT_CHAT,
    },
    {
        id: "23",
        title: "Medium",
        url: "https://medium.com/@therohitdudi",
        icon: "medium",
        visible: true,
        order: 22,
        category: LINK_CATEGORIES.READ_WRITE,
    },
    {
        id: "24",
        title: "Substack",
        url: "https://substack.com/@therohitdudi",
        icon: "substack",
        visible: true,
        order: 23,
        category: LINK_CATEGORIES.READ_WRITE,
    },
    {
        id: "25",
        title: "GoodReads",
        url: "https://www.goodreads.com/therohitdudi",
        icon: "goodreads",
        visible: true,
        order: 24,
        category: LINK_CATEGORIES.READ_WRITE,
    },
    {
        id: "26",
        title: "Pexels",
        url: "https://www.pexels.com/@rohit-dudi-2140783558/",
        icon: "pexels",
        visible: true,
        order: 25,
        category: LINK_CATEGORIES.PROFESSIONAL_CREATIVE,
    },
    {
        id: "27",
        title: "Pixabay",
        url: "https://pixabay.com/users/therohitdudi-28530293/",
        icon: "pixabay",
        visible: true,
        order: 26,
        category: LINK_CATEGORIES.PROFESSIONAL_CREATIVE,
    },
    {
        id: "28",
        title: "Stack Overflow",
        url: "https://stackoverflow.com/users/28278360/rohit-dudi",
        icon: "stackoverflow",
        visible: true,
        order: 27,
        category: LINK_CATEGORIES.PROFESSIONAL_CREATIVE,
    },
    {
        id: "29",
        title: "Minds",
        url: "https://www.minds.com/therohitdudi/",
        icon: "minds",
        visible: true,
        order: 28,
        category: LINK_CATEGORIES.CONNECT_CHAT,
    },
    {
        id: "30",
        title: "VK",
        url: "https://vk.com/therohitdudi",
        icon: "vk",
        visible: true,
        order: 29,
        category: LINK_CATEGORIES.CONNECT_CHAT,
    },
    {
        id: "31",
        title: "Dailymotion",
        url: "https://www.dailymotion.com/user/TheRohitDudi",
        icon: "dailymotion",
        visible: true,
        order: 30,
        category: LINK_CATEGORIES.WATCH_LISTEN,
    },
    {
        id: "32",
        title: "Truth Social",
        url: "https://truthsocial.com/@TheRohitDudi",
        icon: "truthsocial",
        visible: true,
        order: 31,
        category: LINK_CATEGORIES.CONNECT_CHAT,
    },
    {
        id: "33",
        title: "Rumble",
        url: "https://rumble.com/user/realrohitdudi",
        icon: "rumble",
        visible: true,
        order: 32,
        category: LINK_CATEGORIES.WATCH_LISTEN,
    },
    {
        id: "34",
        title: "Locals",
        url: "https://locals.com/profile/realrohitdudi",
        icon: "locals",
        visible: true,
        order: 33,
        category: LINK_CATEGORIES.CONNECT_CHAT,
    },
    {
        id: "35",
        title: "DeviantArt",
        url: "https://www.deviantart.com/rohitdudi",
        icon: "deviantart",
        visible: true,
        order: 34,
        category: LINK_CATEGORIES.PROFESSIONAL_CREATIVE,
    },
    {
        id: "36",
        title: "IMDb",
        url: "https://www.imdb.com/user/p.lxj4jfggsofs4f5t2srnvdjoji",
        icon: "imdb",
        visible: true,
        order: 35,
        category: LINK_CATEGORIES.PROFESSIONAL_CREATIVE,
    },
    {
        id: "37",
        title: "Letterboxd",
        url: "https://letterboxd.com/TheRohitDudi/",
        icon: "letterboxd",
        visible: true,
        order: 36,
        category: LINK_CATEGORIES.PROFESSIONAL_CREATIVE,
    },
];

export const FEATURED_SOCIAL_LINKS = [
    { href: "https://www.instagram.com/TheRohitDudi", icon: "instagram" },
    { href: "https://www.youtube.com/@TheRohitDudi", icon: "youtube" },
    { href: "https://www.facebook.com/profile.php?id=61583425590511", icon: "facebook" },
    { href: "https://x.com/TheRohitDudi", icon: "twitter" },
    { href: "https://in.pinterest.com/TheRohitDudi/", icon: "pinterest" },
];

export const CONTACT_EMAIL = "hello@rohitdudi.com";

export const FOOTER_SITES = [
    { label: "Main Website", href: "https://rohitdudi.com" },
    { label: "Our Studio", href: "https://studios.rohitdudi.com" },
    { label: "Our Agency", href: "https://agency.rohitdudi.com" },
    { label: "My Portfolio", href: "https://dev.rohitdudi.com" },
];

export const DEFAULT_PROFILE = {
    name: "Rohit Dudi",
    bio: "Hey mate! Explore the links & connect with me there.",
    profileImage: "",
};

export const THEME_ACCENT_COLORS = {
    cyan: "#00d9ff",
    purple: "#8b5cf6",
    pink: "#ec4899",
    green: "#10b981",
    orange: "#f97316",
    red: "#ef4444",
};

export const ADMIN_CREDENTIALS = {
    username: "admin",
    password: "admin123", // Edit credentials here only. These are only editable via code.
};
